wordpress_env_defaults:
  db_host: localhost
  db_name: "{{ site | underscore }}_{{ env }}"
  db_user: "{{ site | underscore }}"
  db_user_host: localhost
  disable_wp_cron: true
  wp_env: "{{ env }}"
  wp_home: "{{ project.ssl.enabled | default(false) | ternary('https', 'http') }}://{{ project.site_hosts | map(attribute='canonical') | first }}"
  wp_siteurl: "{{ project.ssl.enabled | default(false) | ternary('https', 'http') }}://{{ project.site_hosts | map(attribute='canonical') | first }}/wp"
  domain_current_site: "{{ project.site_hosts | map(attribute='canonical') | first }}"
wordpress_env: "{{ wordpress_env_defaults | combine(project.env | default({}), vault_apps[site].env) }}"

laravel_env_defaults:
  app_name: Example
  app_env: "{{ env }}"
  app_key: "generateme" # artisan key:generate --show
  app_debug: false
  app_url: https://example.com
  log_channel: stack
  db_connection: mysql
  db_host: localhost
  db_port: 3306
  db_database: "{{ site | underscore }}_{{ env }}"
  db_username: "{{ site | underscore }}"
  broadcast_driver: log
  cache_driver: file
  session_driver: file
  session_lifetime: 120
  queue_driver: sync
  mail_driver: smtp
  mail_host:
  mail_port:
  mail_user:
  mail_password:
  mail_encryption: "null"
laravel_env: "{{ laravel_env_defaults | combine(project.env | default({}), vault_apps[site].env) }}"

app_env: "{% if project.type == 'wordpress' -%}{{ wordpress_env }}{% elif project.type == 'laravel' -%}{{ laravel_env }}{% endif -%}"
