---
- import_playbook: variable-check.yml
  vars:
    playbook: rollback.yml

- name: Test Connection
  hosts: web:&{{ env }}
  gather_facts: false
  vars:
    dynamic_user: false
  roles:
    - { role: connection, tags: [connection, always] }

- name: Set ansible_python_interpreter
  hosts: web:&{{ env }}
  gather_facts: false
  become: yes
  roles:
    - { role: python_interpreter, tags: [always] }

- name: Rollback a Deploy
  hosts: web:&{{ env }}
  remote_user: "{{ web_user }}"
  roles:
    - rollback
