---
- name: "WordPress Server: Install LEMP Stack with PHP 5.6 and MariaDB MySQL"
  hosts: web
  remote_user: root

  roles:
    - { role: kamaln7.swapfile, swapfile_size: 1GB, swapfile_swappiness: 10, when: swap, tags: [swap] }
    - { role: common, tags: [common] }
    - { role: fail2ban, tags: [fail2ban] }
    - { role: ferm, tags: [ferm] }
    - { role: users, tags: [users] }
    - { role: mariadb, tags: [mariadb] }
    - { role: ssmtp, tags: [ssmtp mail] }
    - { role: php, when: not hhvm, tags: [php] }
    - { role: hhvm, when: hhvm, tags: [hhvm] }
    - { role: nginx, tags: [nginx] }
    - { role: memcached, tags: [memcached] }
    - { role: composer, tags: [composer] }
    - { role: wp-cli, tags: [wp-cli] }
    - { role: github-ssh-keys, tags: [github-ssh-keys], when: github_ssh_keys is defined }
    - { role: wordpress-setup, tags: [wordpress, wordpress-setup] }
