---
- name: Install LEMP Stack with PHP 5.5 and MariaDB MySQL
  hosts: wordpress-server
  user: root
  # remote_user: deploy
  # sudo: yes

  roles:
    - common
    - mariadb
    - php-55
    - nginx
    - composer
    - { role: known-hosts, when: wordpress_sites.0.run_composer and known_hosts is defined }
    - dev-tools
    - wp-cli
    - capistrano-setup
    - wordpress-sites
