---
- name: Determine Remote User
  hosts: "{{ xdebug_tunnel_inventory_host }}"
  gather_facts: false
  roles:
    - { role: remote-user, tags: [remote-user, always] }

- name: Enable/Disable Xdebug
  hosts: "{{ xdebug_tunnel_inventory_host }}"
  roles:
    - { role: xdebug, tags: [xdebug] }
  handlers:
    - include: roles/common/handlers/main.yml

- name: Manage XDebug SSH Tunnel
  hosts: localhost
  roles:
    - { role: xdebug-tunnel, tags: [xdebug-tunnel] }
