# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/staging/vault.yml

wordpress_sites:
  example.com:
    site_hosts:
      - canonical: staging.example.com
        # redirects:
        #   - otherdomain.com
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:example/example.com.git # replace with your Git repo URL
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: true
      subdomains: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
    env:
      domain_current_site: staging.example.com
      wp_home: https://staging.example.com
      wp_siteurl: https://staging.example.com/wp
