---
- name: Generate self-signed certificates
  shell: "openssl req -subj \"/CN={{ item.value.site_hosts[0].canonical }}\" -new \
    -newkey rsa:2048 -days 3650 -nodes -x509 -sha256 \
    -extensions req_ext -config <( \
cat <<\" EOF\"\n
[req]\n
distinguished_name = dn\n
[ dn ]\n
[ req_ext ]\n
subjectAltName = {{ site_hosts | union(multisite_subdomains_wildcards) | map('regex_replace', '(.*)', 'DNS:\\1') | join(',') }}\n
EOF\n
    ) \
    -keyout {{ item.key | quote }}.key -out {{ item.key | quote }}.cert"
  args:
    executable: "/bin/bash"
    chdir: "{{ nginx_path }}/ssl"
    creates: "{{ item.key }}.*"
  with_dict: "{{ wordpress_sites }}"
  when: ssl_enabled and item.value.ssl.provider | default('manual') == 'self-signed'
  notify: reload nginx
