wordpress_env_defaults:
  db_host: localhost
  db_name: "{{ item.key | underscore }}_{{ env }}"
  db_user: "{{ item.key | underscore }}"
  db_user_host: localhost
  disable_wp_cron: true
  wp_env: "{{ env }}"
  wp_home: "{{ ssl_enabled | ternary('https', 'http') }}://{{ site_hosts_canonical | first }}"
  wp_siteurl: "{{ ssl_enabled | ternary('https', 'http') }}://{{ site_hosts_canonical | first }}/wp"
  multisite: "{{ item.value.multisite.enabled | default(false) }}"
  subdomain_install: "{{ item.value.multisite.enabled | default(false) | ternary(item.value.multisite.subdomains | default(false), false) }}"
  domain_current_site: "{{ site_hosts_canonical | first }}"
  path_current_site: "{{ item.value.multisite.base_path | default('/') }}"

site_env: "{{ wordpress_env_defaults | combine(item.value.env | default({}), vault_wordpress_sites[item.key].env) }}"
site_hosts_canonical: "{{ item.value.site_hosts | map(attribute='canonical') | list }}"
site_hosts_redirects: "{{ item.value.site_hosts | selectattr('redirects', 'defined') | sum(attribute='redirects', start=[]) | list }}"
site_hosts: "{{ site_hosts_canonical | union(site_hosts_redirects) }}"
ssl_enabled: "{{ item.value.ssl is defined and item.value.ssl.enabled | default(false) }}"
