ferm_input_list:
  - type: dport_accept
    dport: [http, https]
    filename: nginx_accept
  - type: dport_accept
    dport: [ssh]
    saddr: "{{ ip_whitelist }}"
  - type: dport_limit
    dport: [ssh]
    seconds: 300
    hits: 20

# Documentation: https://roots.io/trellis/docs/security/
# If ssh_allow_root_with_key: false, admin_user must be in 'users' (`group_vars/all/users.yml`) with sudo group
# and in 'vault_users' (`group_vars/staging/vault.yml`, `group_vars/production/vault.yml`)
ssh_allow_root_with_key: true
ssh_server_password_login: false
# If sftp_enabled: false, you have to uncomment scp_if_ssh = True in your ansible.cfg. This way Ansible uses
# SCP to copy files instead of the default SFTP.
sftp_enabled: true
