---
- name: Create XDebug SSH Tunnel
  command: "ssh -M -S '{{ xdebug_tunnel_control_socket }}' -fnNT -L {{ xdebug_tunnel_remote_port }}:{{ xdebug_tunnel_host }}:{{ xdebug_tunnel_local_port }} {{ hostvars[xdebug_tunnel_ssh_host]['ansible_user'] | default(admin_user) }}@{{ hostvars[xdebug_tunnel_ssh_host]['ansible_host'] }} '{{ xdebug_tunnel_control_identity }}'"
  when: xdebug_tunnel_close == false
  register: xdebug_tunnel_creation
  ignore_errors: true

- name: Fail the play if tunnel already exists
  fail: msg="SSH tunnel already exists! Refer to TODO for help. Error:\n{{ xdebug_tunnel_creation.stderr | default('') }}"
  when: "'bind: Address already in use' in xdebug_tunnel_creation.stderr | default('')"
