acme_tiny_challenges_directory: "{{ www_root }}/letsencrypt"
env: development
ferm_enabled: false
ip_whitelist: "{{ ansible_control_node_ip }}"
mysql_root_password: "{{ vault_mysql_root_password }}" # Define this variable in group_vars/development/vault.yml
web_user: vagrant
