---
- name: Ensure SSL directories exist
  file:
    path: "{{ nginx_ssl_path }}/manual-certificates"
    state: directory
    mode: 0700
  when: site_uses_manual_certificates
  with_dict: "{{ wordpress_sites }}"

- name: Copy SSL cert
  copy:
    src: "{{ item.value.ssl.cert }}"
    dest: "{{ nginx_ssl_path }}/manual-certificates/{{ item.value.ssl.cert | basename }}"
    mode: 0640
  with_dict: "{{ wordpress_sites }}"
  when: site_uses_manual_certificates and item.value.ssl.cert is defined

- name: Copy SSL key
  copy:
    src: "{{ item.value.ssl.key }}"
    dest: "{{ nginx_ssl_path }}/manual-certificates/{{ item.value.ssl.key | basename }}"
    mode: 0600
  with_dict: "{{ wordpress_sites }}"
  when: site_uses_manual_certificates and item.value.ssl.key is defined
