---
- name: disable temporary challenge sites
  import_tasks: disable_challenge_sites.yml

- name: restart memcached
  service:
    name: memcached
    state: restarted

- name: restart redis
  service:
    name: redis_{{ redis_port }}
    state: restarted

- name: restart sentinel
  service:
    name: sentinel_{{ redis_sentinel_port }}
    state: restarted

- name: reload php-fpm
  service:
    name: php7.3-fpm
    state: reloaded

- import_tasks: reload_nginx.yml
