---
- name: Require manual definition of remote-user
  fail:
    msg: |
      When using `--ask-pass` option, use `-u` option to define remote-user:
      ansible-playbook server.yml -e env={{ env }} -u username --ask-pass
  when: cli_options | search('--ask-pass')

- name: Determine whether to connect as root or admin_user
  local_action: command ansible {{ inventory_hostname }} -m raw -a whoami -u {{ ansible_user | default('root') }} {{ cli_options | default('') }}
  failed_when: false
  changed_when: false
  register: root_status

- name: Set remote user for each host
  set_fact:
    ansible_user: "{{ ('root' in root_status.stdout_lines) | ternary(ansible_user | default('root'), admin_user) }}"

- name: Announce which user was selected
  debug:
    msg: "Note: Ansible will attempt connections as user = {{ ansible_user }}"
