---
- name: Update Apt
  apt: update_cache=yes

- name: Checking essentials
  apt: name="{{ item }}" state=present
  with_items:
  - python-software-properties
  - python-pycurl
  - build-essential
  - python-mysqldb
  - curl
  - git-core
  - npm
  - nodejs-legacy
  - mailutils

- name: Install bower
  npm: name=bower global=yes state=present

- name: Install grunt
  npm: name=grunt-cli global=yes state=present
